/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSTitledFrame.h"

@class NSButton, NSString;

@interface NSThemeFrame : NSTitledFrame
{
    NSButton *toolbarButton;
    int toolbarVisibleStatus;
    struct CGLayer *showToolbarTransitionLayer;
    struct CGSize showToolbarPreWindowSize;
    NSButton *modeButton;
    long long leftGroupTrackingTagNum;
    long long rightGroupTrackingTagNum;
    struct {
        unsigned int mouseInsideLeftGroup:1;
        unsigned int mouseInsideRightGroup:1;
        unsigned int bottomCornerRounded:2;
        unsigned int movableByBottomBar:1;
        unsigned int reserved:27;
    } _tFlags;
    int widgetState;
    NSString *displayName;
    NSButton *lockButton;
    double topBorderThickness;
    double bottomBorderThickness;
}

+ (void)initialize;	// IMP=0x00021662
+ (id)_bevelForEdge:(unsigned long long)arg1 isHUD:(BOOL)arg2 isDarkWindow:(BOOL)arg3;	// IMP=0x002635f4
+ (void)drawBevel:(struct CGRect)arg1 inFrame:(struct CGRect)arg2 topCornerRounded:(BOOL)arg3 bottomCornerRounded:(BOOL)arg4 isHUD:(BOOL)arg5 isDarkWindow:(BOOL)arg6;	// IMP=0x0026256f
+ (void)drawBevel:(struct CGRect)arg1 inFrame:(struct CGRect)arg2 topCornerRounded:(BOOL)arg3 bottomCornerRounded:(BOOL)arg4;	// IMP=0x005c519c
+ (double)_windowBorderThickness:(unsigned long long)arg1;	// IMP=0x00046a44
+ (double)_minXWindowBorderWidth:(unsigned long long)arg1;	// IMP=0x0008678e
+ (double)_maxXWindowBorderWidth:(unsigned long long)arg1;	// IMP=0x00046a18
+ (double)_minYWindowBorderHeight:(unsigned long long)arg1;	// IMP=0x005c472a
+ (double)_windowTitlebarButtonSpacingWidth:(unsigned long long)arg1;	// IMP=0x005c4734
+ (double)_windowFileButtonSpacingWidth:(unsigned long long)arg1;	// IMP=0x005c4751
+ (double)_minXTitlebarWidgetInset:(unsigned long long)arg1;	// IMP=0x005c475f
+ (double)_maxXTitlebarWidgetInset:(unsigned long long)arg1;	// IMP=0x005c478b
+ (double)minFrameWidthWithTitle:(id)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x005c4c9f
+ (double)_windowSideTitlebarTitleMinWidth:(unsigned long long)arg1;	// IMP=0x0004694c
+ (double)_windowTitlebarTitleMinHeight:(unsigned long long)arg1;	// IMP=0x0004f86b
+ (double)_sideTitlebarWidth:(unsigned long long)arg1;	// IMP=0x0004693a
+ (double)_titlebarHeight:(unsigned long long)arg1;	// IMP=0x0004f859
+ (double)_resizeHeight:(unsigned long long)arg1;	// IMP=0x000469f8
+ (BOOL)_resizeFromEdge;	// IMP=0x0023fb22
+ (struct CGSize)sizeOfTitlebarButtons:(unsigned long long)arg1;	// IMP=0x0004bc26
+ (double)_contentToFrameMinXWidth:(unsigned long long)arg1;	// IMP=0x0004691a
+ (double)_contentToFrameMaxXWidth:(unsigned long long)arg1;	// IMP=0x00046a05
+ (double)_contentToFrameMinYHeight:(unsigned long long)arg1;	// IMP=0x000469e4
+ (double)_contentToFrameMaxYHeight:(unsigned long long)arg1;	// IMP=0x00046a25
+ (unsigned long long)_validateStyleMask:(unsigned long long)arg1;	// IMP=0x00045d9a
- (BOOL)_isDarkWindow;	// IMP=0x00086b7a
- (BOOL)_movableByBottomBar;	// IMP=0x000b6457
- (void)_setMovableByBottomBar:(BOOL)arg1;	// IMP=0x005c46da
- (BOOL)_effectiveMovableByBottomBar;	// IMP=0x000882b8
- (float)roundedCornerRadius;	// IMP=0x00086b50
- (void)setBottomCornerRounded:(BOOL)arg1;	// IMP=0x002109e2
- (BOOL)bottomCornerRounded;	// IMP=0x00050fed
- (struct CGSize)_topCornerSize;	// IMP=0x00086ab6
- (struct CGSize)_bottomCornerSize;	// IMP=0x00086b9c
- (void *)_createWindowOpaqueShape;	// IMP=0x00086941
- (void)shapeWindow;	// IMP=0x00050a0b
- (void)_recursiveDisplayRectIfNeededIgnoringOpacity:(struct CGRect)arg1 isVisibleRect:(BOOL)arg2 rectIsVisibleRectForView:(id)arg3 topView:(BOOL)arg4;	// IMP=0x000fddea
- (struct CGRect)overlayBounds;	// IMP=0x00133696
- (void)drawOverlayRect:(struct CGRect)arg1;	// IMP=0x0013394a
- (void *)_regionForOpaqueDescendants:(struct CGRect)arg1 forMove:(BOOL)arg2;	// IMP=0x0008839c
- (void)_drawFrameInterior:(struct CGRect *)arg1 clip:(struct CGRect)arg2;	// IMP=0x001027ca
- (void)_setTextShadow:(BOOL)arg1;	// IMP=0x005c5da1
- (BOOL)_isOnePieceTitleAndToolbar;	// IMP=0x00088329
- (struct CGRect)_separatorRectForInactiveWindow;	// IMP=0x00262420
- (void)_setFrameNeedsDisplay:(BOOL)arg1;	// IMP=0x000f3a37
- (void)_drawUnifiedToolbarBackgroundInRect:(struct CGRect)arg1 withState:(long long)arg2;	// IMP=0x005c6266
- (void)_drawUnifiedToolbar:(int)arg1;	// IMP=0x0010300b
- (void)_drawTitleBar:(struct CGRect)arg1;	// IMP=0x00102818
- (void)_drawResizeIndicators:(struct CGRect)arg1;	// IMP=0x00133b2d
- (void)_drawFrameRects:(struct CGRect)arg1;	// IMP=0x005c6cdb
- (void)drawFrame:(struct CGRect)arg1;	// IMP=0x00102402
- (BOOL)_isHUDWindow;	// IMP=0x00047348
- (id)contentFill;	// IMP=0x000fd96f
- (void)viewDidEndLiveResize;	// IMP=0x005c514f
- (double)contentAlpha;	// IMP=0x00086c26
- (void)setThemeFrameWidgetState:(int)arg1;	// IMP=0x005c5133
- (BOOL)constrainResizeEdge:(unsigned long long *)arg1 withDelta:(struct CGSize)arg2 elapsedTime:(double)arg3;	// IMP=0x005c46fb
- (void)addFileButton:(id)arg1;	// IMP=0x005c50e9
- (void)_updateButtons;	// IMP=0x00046d6f
- (void)_updateButtonState;	// IMP=0x00275e97
- (id)newCloseButton;	// IMP=0x000473ed
- (id)newZoomButton;	// IMP=0x0004aba1
- (id)newMiniaturizeButton;	// IMP=0x0004ace1
- (id)newToolbarButton;	// IMP=0x000aab85
- (id)newLockButton;	// IMP=0x005c5075
- (id)newFileButton;	// IMP=0x000ebe49
- (void)_resetTitleBarButtons;	// IMP=0x005c4f73
- (void)setDocumentEdited:(BOOL)arg1;	// IMP=0x001bf288
- (id)toolbarButton;	// IMP=0x000aad7a
- (id)lockButton;	// IMP=0x005c4707
- (id)modeButton;	// IMP=0x0019a9f0
- (id)initWithFrame:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 owner:(id)arg3;	// IMP=0x00046a51
- (void)setStyleMask:(unsigned long long)arg1;	// IMP=0x002874c0
- (void)viewWillMoveToWindow:(id)arg1;	// IMP=0x00046cd8
- (void)dealloc;	// IMP=0x001a6e9a
- (BOOL)preservesContentDuringLiveResize;	// IMP=0x005c4f59
- (void)setFrameSize:(struct CGSize)arg1;	// IMP=0x0004f918
- (BOOL)_canHaveToolbar;	// IMP=0x0008da95
- (BOOL)_toolbarIsInTransition;	// IMP=0x0004ec14
- (BOOL)_toolbarIsShown;	// IMP=0x0008dabc
- (BOOL)_toolbarIsHidden;	// IMP=0x000f3c5c
- (id)_toolbarView;	// IMP=0x000882fb
- (id)_toolbar;	// IMP=0x000a9a3c
- (double)_distanceFromToolbarBaseToTitlebar;	// IMP=0x0004e30b
- (unsigned long long)_shadowFlags;	// IMP=0x00134aab
- (struct CGRect)frameRectForContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x000ccf88
- (struct CGRect)contentRectForFrameRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0004e0de
- (struct CGSize)minFrameSizeForMinContentSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x005c4ec5
- (struct CGRect)contentRect;	// IMP=0x00102399
- (struct CGRect)_contentRectExcludingToolbar;	// IMP=0x000a9bf4
- (struct CGRect)_contentRectIncludingToolbarAtHome;	// IMP=0x000a9b8e
- (void)_setToolbarShowHideResizeWeightingOptimizationOn:(BOOL)arg1;	// IMP=0x000a9ad9
- (BOOL)_usingToolbarShowHideWeightingOptimization;	// IMP=0x0016d5c9
- (void)handleSetFrameCommonRedisplay;	// IMP=0x0016d4e2
- (void)_startLiveResizeAsTopLevel;	// IMP=0x005c4e63
- (void)_endLiveResizeAsTopLevel;	// IMP=0x005c4e11
- (void)_growContentReshapeContentAndToolbarView:(int)arg1 animate:(BOOL)arg2;	// IMP=0x005c65c8
- (BOOL)_growWindowReshapeContentAndToolbarView:(int)arg1 animate:(BOOL)arg2;	// IMP=0x000a8ccd
- (void)_reshapeContentAndToolbarView:(int)arg1 resizeWindow:(BOOL)arg2 animate:(BOOL)arg3;	// IMP=0x000a8b15
- (void)_toolbarFrameSizeChanged:(id)arg1 oldSize:(struct CGSize)arg2;	// IMP=0x005c648c
- (void)_syncToolbarPosition;	// IMP=0x002832ec
- (void)_showHideToolbar:(int)arg1 resizeWindow:(BOOL)arg2 animate:(BOOL)arg3;	// IMP=0x000a75cc
- (void)_showToolbarWithAnimation:(BOOL)arg1;	// IMP=0x000a7506
- (void)_hideToolbarWithAnimation:(BOOL)arg1;	// IMP=0x005c5e32
- (void)_drawToolbarTransitionIfNecessary;	// IMP=0x0010808f
- (void)_computeHeightOfTop:(BOOL)arg1 bottom:(BOOL)arg2;	// IMP=0x0004dbb9
- (void)setContentBorderThickness:(double)arg1 forEdge:(unsigned long long)arg2;	// IMP=0x000b5e6b
- (double)contentBorderThicknessForEdge:(unsigned long long)arg1;	// IMP=0x0004aaf5
- (double)_topBarHeight;	// IMP=0x000b6477
- (double)_bottomBarHeight;	// IMP=0x00051075
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x00101a38
- (void)drawWindowBackgroundRect:(struct CGRect)arg1;	// IMP=0x0013a60f
- (void)drawWindowBackgroundRegion:(void *)arg1;	// IMP=0x00107e12
- (BOOL)shouldBeTreatedAsInkEvent:(id)arg1;	// IMP=0x005c4718
- (BOOL)_shouldBeTreatedAsInkEventInInactiveWindow:(id)arg1;	// IMP=0x005c4720
- (id)hitTest:(struct CGPoint)arg1;	// IMP=0x00139672
- (void)cursorUpdate:(id)arg1;	// IMP=0x00229aa4
- (struct CGRect)_leftGroupRect;	// IMP=0x0004c2b2
- (struct CGRect)_rightGroupRect;	// IMP=0x0004cc9e
- (void)_updateWidgets;	// IMP=0x0004cd95
- (void)_updateMouseTracking;	// IMP=0x0004c0fc
- (void)mouseEntered:(id)arg1;	// IMP=0x0026bb18
- (void)mouseExited:(id)arg1;	// IMP=0x0026bb56
- (void)_setMouseEnteredGroup:(BOOL)arg1 entered:(BOOL)arg2;	// IMP=0x0004d1cf
- (BOOL)_mouseInGroup:(id)arg1;	// IMP=0x00109194
- (struct CGSize)miniaturizedSize;	// IMP=0x005c6222
- (double)_minXTitlebarDecorationMinWidth;	// IMP=0x000f21d2
- (double)_maxXTitlebarDecorationMinWidth;	// IMP=0x000f241d
- (struct CGSize)minFrameSize;	// IMP=0x005c4b6d
- (double)_windowBorderThickness;	// IMP=0x005c47a9
- (double)_windowTitlebarXResizeBorderThickness;	// IMP=0x005c47b3
- (double)_windowTitlebarYResizeBorderThickness;	// IMP=0x005c47bd
- (double)_windowResizeBorderThickness;	// IMP=0x005c47c7
- (double)_minXWindowBorderWidth;	// IMP=0x000868cd
- (double)_maxXWindowBorderWidth;	// IMP=0x000868d7
- (double)_minYWindowBorderHeight;	// IMP=0x0004bb11
- (double)_maxYWindowBorderHeight;	// IMP=0x0004bb5b
- (double)_minYTitlebarButtonsOffset;	// IMP=0x000868e1
- (double)_minYTitlebarTitleOffset;	// IMP=0x005c47d1
- (double)_sideTitlebarWidth;	// IMP=0x0004bb1e
- (double)_titlebarHeight;	// IMP=0x0004f81b
- (struct CGRect)_defaultTitlebarTitleRect;	// IMP=0x000ec2aa
- (struct CGRect)_titlebarTitleRect;	// IMP=0x000ec1d8
- (struct CGRect)titlebarRect;	// IMP=0x0004b997
- (double)_windowTitlebarTitleMinHeight;	// IMP=0x005c4b30
- (struct CGSize)_sizeOfTitlebarFileButton;	// IMP=0x000f23dc
- (struct CGSize)sizeOfTitlebarToolbarButton;	// IMP=0x000f249b
- (double)_windowTitlebarButtonSpacingWidth;	// IMP=0x0004bf20
- (double)_windowFileButtonSpacingWidth;	// IMP=0x000f240f
- (double)_minXTitlebarWidgetInset;	// IMP=0x0004bb65
- (double)_maxXTitlebarWidgetInset;	// IMP=0x000f24d9
- (double)_minXTitlebarButtonsWidth;	// IMP=0x000f226c
- (double)_maxXTitlebarButtonsWidth;	// IMP=0x000f242f
- (struct CGPoint)_closeButtonOrigin;	// IMP=0x0004b730
- (struct CGPoint)_zoomButtonOrigin;	// IMP=0x0004bf49
- (struct CGPoint)_collapseButtonOrigin;	// IMP=0x0004bd88
- (struct CGPoint)_toolbarButtonOrigin;	// IMP=0x000aabfc
- (struct CGPoint)_lockButtonOrigin;	// IMP=0x005c6b08
- (struct CGPoint)_fileButtonOrigin;	// IMP=0x000ec09d
- (void)_tileTitlebarAndRedisplay:(BOOL)arg1;	// IMP=0x0004b378
- (struct CGRect)_commandPopupRect;	// IMP=0x000f2b12
- (struct CGRect)_draggableFrame;	// IMP=0x0008804f
- (void)_resetDragMargins;	// IMP=0x0004d369
- (double)_maxYTitlebarDragHeight;	// IMP=0x005c4b1e
- (double)_minXTitlebarDragWidth;	// IMP=0x005c4b0d
- (double)_maxXTitlebarDragWidth;	// IMP=0x005c4afc
- (double)_contentToFrameMinXWidth;	// IMP=0x000a9d69
- (double)_contentToFrameMaxXWidth;	// IMP=0x000a9db8
- (double)_contentToFrameMinYHeight;	// IMP=0x000a9da7
- (double)_contentToFrameMaxYHeight;	// IMP=0x000a9dca
- (double)_windowResizeCornerThickness;	// IMP=0x005c47e1
- (struct CGRect)_minYResizeRect;	// IMP=0x005c47eb
- (struct CGRect)_minYminXResizeRect;	// IMP=0x0023fbb5
- (struct CGRect)_minYmaxXResizeRect;	// IMP=0x0023fbe3
- (struct CGRect)_minXResizeRect;	// IMP=0x005c4819
- (struct CGRect)_minXminYResizeRect;	// IMP=0x0023fb2b
- (struct CGRect)_minXmaxYResizeRect;	// IMP=0x0023fb59
- (struct CGRect)_maxYResizeRect;	// IMP=0x005c4847
- (struct CGRect)_maxYminXResizeRect;	// IMP=0x0023fc11
- (struct CGRect)_maxYmaxXResizeRect;	// IMP=0x0023fc3f
- (struct CGRect)_maxXResizeRect;	// IMP=0x005c4875
- (struct CGRect)_maxXminYResizeRect;	// IMP=0x00050e0f
- (struct CGRect)_maxXmaxYResizeRect;	// IMP=0x0023fb87
- (struct CGRect)_minXTitlebarResizeRect;	// IMP=0x005c48a5
- (struct CGRect)_maxXTitlebarResizeRect;	// IMP=0x005c48d3
- (struct CGRect)_minXBorderRect;	// IMP=0x005c57a3
- (struct CGRect)_maxXBorderRect;	// IMP=0x005c4901
- (struct CGRect)_maxYBorderRect;	// IMP=0x005c56b7
- (struct CGRect)_minYBorderRect;	// IMP=0x005c55cc
- (void)_invalidateTitleCellSize;	// IMP=0x00046d47
- (void)_resetTitleFont;	// IMP=0x005c4a8d
- (BOOL)_isUtility;	// IMP=0x0004adc9
- (double)_sheetHeightAdjustment;	// IMP=0x002832b5
- (void)_setSheet:(BOOL)arg1;	// IMP=0x0027d4da
- (BOOL)_isSheet;	// IMP=0x0004731c
- (BOOL)_isResizable;	// IMP=0x0004acc7
- (BOOL)_isClosable;	// IMP=0x00047363
- (BOOL)_isMiniaturizable;	// IMP=0x0004ad56
- (BOOL)_hasToolbar;	// IMP=0x0004737c
- (struct CGRect)_growBoxRect;	// IMP=0x00050bfc
- (BOOL)_canDrawWindowGrowBox;	// IMP=0x0011c6b2
- (void)_drawGrowBoxWithClip:(struct CGRect)arg1 inRect:(struct CGRect)arg2 opaque:(BOOL)arg3;	// IMP=0x00133c67
- (void)_drawGrowBoxWithClip:(struct CGRect)arg1;	// IMP=0x00133bad
- (BOOL)_inactiveButtonsNeedMask;	// IMP=0x005c4931
- (BOOL)_mouseInPopupRect:(id)arg1;	// IMP=0x005c614c
- (BOOL)_mouseInTitleRect:(id)arg1;	// IMP=0x005c6077
- (void)mouseDown:(id)arg1;	// IMP=0x0023f2f2
- (void)rightMouseDown:(id)arg1;	// IMP=0x005c4a06
- (id)menu;	// IMP=0x005c4950
- (id)menuForEvent:(id)arg1;	// IMP=0x005c5ecc
- (id)_displayName;	// IMP=0x005c493c
- (void)_setDisplayName:(id)arg1;	// IMP=0x00203e15
- (BOOL)_shouldRepresentFilename;	// IMP=0x005c5432
- (BOOL)_shouldShowDocumentIcon;	// IMP=0x0004b31f
- (void)setRepresentedURL:(id)arg1;	// IMP=0x000ebd03
- (void)setRepresentedFilename:(id)arg1;	// IMP=0x005c53a4

@end

